const defaultListings=[
{id:1,type:"Sotiladi",title:"3 xonali shinam kvartira",region:"Toshkent shahri",price:"650 000 000",rooms:"3 xona",area:"78 m²",phone:"+998 90 123 45 67",image:"https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80",desc:"Yaxshi ta’mirlangan, qulay joylashuvdagi shinam kvartira."},
{id:2,type:"Ijaraga beriladi",title:"Yangi 2 xonali kvartira",region:"Samarqand",price:"3 500 000 / oy",rooms:"2 xona",area:"65 m²",phone:"+998 91 234 56 78",image:"https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=80",desc:"Yangi ta’mirlangan kvartira, mebel va texnika bilan."},
{id:3,type:"Sotiladi",title:"Keng hovli uy",region:"Farg‘ona",price:"480 000 000",rooms:"5+ xona",area:"210 m²",phone:"+998 93 345 67 89",image:"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80",desc:"Oilaviy yashash uchun katta hovli va barcha qulayliklar."}
];
function getListings(){let x=localStorage.getItem("joylashListings");if(!x){localStorage.setItem("joylashListings",JSON.stringify(defaultListings));return defaultListings}return JSON.parse(x)}
function saveListings(x){localStorage.setItem("joylashListings",JSON.stringify(x))}
function card(x){return `<article class="card"><div class="card-img" style="background-image:url('${x.image||"https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=80"}')"><span class="tag">${x.type}</span></div><div class="card-body"><div class="price">${x.price} so‘m</div><h3>${x.title}</h3><div class="meta">📍 ${x.region} &nbsp; • &nbsp; 🛏 ${x.rooms} &nbsp; • &nbsp; 📐 ${x.area}</div><a class="phone" href="tel:${x.phone.replace(/\s/g,'')}">📞 ${x.phone}</a></div></article>`}
function renderListings(id,limit){let arr=getListings().slice().reverse();if(limit)arr=arr.slice(0,limit);document.getElementById(id).innerHTML=arr.length?arr.map(card).join(""):"<p>E’lon topilmadi.</p>"}
function filterListings(){let q=(document.getElementById("search").value||"").toLowerCase(),t=document.getElementById("type").value,r=document.getElementById("region").value;let arr=getListings().filter(x=>(!q||(x.title+" "+x.region+" "+x.desc).toLowerCase().includes(q))&&(!t||x.type===t)&&(!r||x.region===r));document.getElementById("listingGrid").innerHTML=arr.length?arr.reverse().map(card).join(""):"<p>E’lon topilmadi.</p>"}
function register(e){e.preventDefault();let u={name:regName.value,phone:regPhone.value,pass:regPass.value};localStorage.setItem("joylashUser",JSON.stringify(u));regMsg.textContent="Ro‘yxatdan o‘tish muvaffaqiyatli!";setTimeout(()=>location.href="login.html",700)}
function login(e){e.preventDefault();let u=JSON.parse(localStorage.getItem("joylashUser")||"null"),name=loginUser.value,pass=loginPass.value;if(name==="admin"&&pass==="admin"){location.href="admin.html";return}if(u&&(name===u.phone||name===u.name)&&pass===u.pass){localStorage.setItem("joylashLogged","1");location.href="index.html"}else loginMsg.textContent="Telefon/email yoki parol noto‘g‘ri."}
function addListing(e){e.preventDefault();let x={id:Date.now(),type:aType.value,title:aTitle.value,region:aRegion.value,price:aPrice.value,rooms:aRooms.value,area:aArea.value+" m²",phone:aPhone.value,image:aImage.value,desc:aDesc.value};let arr=getListings();arr.push(x);saveListings(arr);addMsg.textContent="✓ E’lon muvaffaqiyatli joylandi!";setTimeout(()=>location.href="listing.html",800)}
function clearListings(){if(confirm("Barcha demo e’lonlar o‘chirilsinmi?")){localStorage.removeItem("joylashListings");location.reload()}}
